apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
  annotations:
    # When the collector configuration is changed, this value on the Deployment resource
    # will change, and the deployment will be rolled. See:
    # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
    checksum/config: {{ include (print $.Template.BasePath "/singleton-collector-config-map.yaml") . | sha256sum }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}-collector
  template:
    metadata:
      labels:
{{ include "common.template-labels" . | indent 8 }}
        app: {{ include "common.fullname" . }}-collector
    spec:
      serviceAccountName: {{ include "common.fullname" . }}-collector
      securityContext: {}
      containers:
        - name: opentelemetry-collector
          command:
            - /swi-otelcol
            - --config=/conf/relay.yaml
          securityContext: {}
          image: {{ .Values.otel.container_image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SOLARWINDS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: solarwinds-api-token
                  key: SOLARWINDS_API_TOKEN
                  optional: true
            - name: PROMETHEUS_URL
              value: {{ quote .Values.prometheus_url }}
            - name: OTEL_ENVOY_ADDRESS
              value: {{ quote .Values.otel.endpoint }}
            - name: OTEL_ENVOY_ADDRESS_TLS_INSECURE
              value: {{ quote .Values.otel.tls_insecure }}
            - name: CLUSTER_NAME
              value: {{ quote .Values.cluster.name }}
            - name: CLUSTER_UID
              value: {{ quote .Values.cluster.uid }}
            - name: SCRAPE_INTERVAL
              value: {{ quote .Values.otel.singleton_collector.scrape_interval }}
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          resources:
            limits:
              memory: {{ .Values.otel.singleton_collector.resources.limits.memory }}
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
              readOnly: true
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: {{ include "common.fullname" . }}-singleton-collector-config
            items:
              - key: metrics.config
                path: relay.yaml