apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-logs-collector-config
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  logs.config: |
{{ .Files.Get "logs-collector-config.yaml" | indent 8 }}