apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-singleton-collector-config
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  metrics.config: |
{{ .Files.Get "singleton-collector-config.yaml" | indent 8 }}