# This values file provides the default values for the chart. Placeholders like
# <PROMETHEUS_URL> will be provided via the values.yaml provided during the cluster
# onboarding process--or you can provide your own with the appropriate values
# given to you during initial onboarding for an initial cluster and region.

nameOverride: # ""
fullnameOverride: # ""

prometheus_url: <PROMETHEUS_URL>

otel:
  endpoint: <OTEL_API_ENDPOINT> # e.g. otel-collector.dc-01.cloud.solarwinds.com:443
  tls_insecure: false
  container_image: solarwinds/swi-opentelemetry-collector:0.1.4
  # singleton prometheus scraper deployment
  singleton_collector:
    scrape_interval: 60s
    resources:
      limits:
        # override if your singleton collector is being OOM-killed.
        memory: 4Gi
  # logs daemonset
  logs_collector:
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 1000m
        memory: 1Gi

cluster:
  name: <KUBERNETES_CLUSTER_NAME>
  uid: <CLUSTER_UID>
